#!/usr/bin/env node
/**
 * Build-time bundler for the world map.
 *
 *   - Reads the canonical map source (src/map_data.ts or a JSON file passed as argv[2]).
 *   - Encodes the wall grid as run-length compressed base64 (8 bits per tile).
 *   - Emits src/map_bundle.ts containing the elements array, custom tile palette,
 *     and the compact RLE blob. Both client and server import this module — the
 *     map ships with the client bundle and is no longer streamed from the server.
 *
 * Usage:
 *   node scripts/encodeMap.js [input.json] [-o src/map_bundle.ts]
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const args = process.argv.slice(2);
let input = path.join(ROOT, 'src', 'map_data.ts');
let output = path.join(ROOT, 'src', 'map_bundle.ts');
for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '-o' || a === '--output') {
        output = path.resolve(args[++i]);
    } else if (!a.startsWith('-')) {
        input = path.resolve(a);
    }
}

function loadMapData(file) {
    const ext = path.extname(file).toLowerCase();
    const raw = fs.readFileSync(file, 'utf8');
    if (ext === '.json') return JSON.parse(raw);
    // Strip the TS wrapper around the JSON literal.
    const m = raw.match(/const WORLD_MAP_DATA\s*:\s*MapData\s*=\s*(\{[\s\S]*?\});\s*\n/);
    if (!m) throw new Error(`Could not locate WORLD_MAP_DATA literal in ${file}`);
    return JSON.parse(m[1]);
}

// --- Run-length encoder (mirrors decodeTileGridRLE in src/constants.ts) ---
function encodeTileGridRLE(flat) {
    const out = [];
    let i = 0;
    const len = flat.length;
    while (i < len) {
        const v = flat[i] & 0xff;
        let run = 1;
        while (i + run < len && (flat[i + run] & 0xff) === v && run < 0x7fffff) run++;
        i += run;
        while (run > 0) {
            const base = Math.min(127, run);
            const ext = Math.min(0xffff, run - base);
            if (ext > 0) {
                out.push(((base << 1) | 1) & 0xff, (ext >> 8) & 0xff, ext & 0xff, v);
                run -= base + ext;
            } else {
                out.push((base << 1) & 0xff, v);
                run -= base;
            }
        }
    }
    return Buffer.from(out).toString('base64');
}

function flattenWallGrid(grid, width, height) {
    const flat = new Uint8Array(width * height);
    for (let y = 0; y < height; y++) {
        const row = grid[y] || [];
        for (let x = 0; x < width; x++) flat[y * width + x] = (row[x] | 0) & 0xff;
    }
    return flat;
}

function emitBundle({ elements, customTileTypes, rle, width, height, sourceTilesBytes, rleBytes }) {
    const elementsJson = JSON.stringify(elements, null, 2);
    const tilesJson = JSON.stringify(customTileTypes, null, 2);
    const banner = `// AUTO-GENERATED by scripts/encodeMap.js — DO NOT EDIT BY HAND.
// Source: ${path.relative(ROOT, input)}
// Tile grid: ${width}x${height} = ${width * height} tiles, 8 bits each.
// Raw size: ${sourceTilesBytes} bytes  →  RLE+base64: ${rleBytes} bytes (${(100 * rleBytes / sourceTilesBytes).toFixed(1)}%).
`;
    const body = `${banner}
import { MapElement, TileTypeConfig } from './constants';

/** Map elements (spawn zones, biomes, teleporters, safe zones). */
export const MAP_ELEMENTS: MapElement[] = ${elementsJson};

/** Custom tile palette layered on top of the built-in air/wall/water set. */
export const MAP_CUSTOM_TILE_TYPES: TileTypeConfig[] = ${tilesJson};

/** Wall grid dimensions matching constants.WALL_GRID_WIDTH / WALL_GRID_HEIGHT. */
export const MAP_GRID_WIDTH = ${width};
export const MAP_GRID_HEIGHT = ${height};

/** Run-length encoded base64 blob — decode via constants.decodeTileGridRLE(). */
export const MAP_TILE_RLE = ${JSON.stringify(rle)};
`;
    fs.writeFileSync(output, body);
    return body.length;
}

(function main() {
    console.log(`[encodeMap] reading: ${path.relative(ROOT, input)}`);
    const data = loadMapData(input);

    if (!Array.isArray(data.elements)) throw new Error('input has no .elements array');
    const wallGrid = data.wallGrid;
    if (!Array.isArray(wallGrid) || !Array.isArray(wallGrid[0])) {
        throw new Error('input has no .wallGrid 2D array');
    }
    const height = wallGrid.length;
    const width = wallGrid[0].length;

    const customTileTypes = Array.isArray(data.customTileTypes) ? data.customTileTypes : [];
    // Defensive: drop any entries that try to redefine built-ins.
    const customFiltered = customTileTypes.filter(t => t && Number.isInteger(t.id) && t.id >= 3 && t.id <= 255);

    const flat = flattenWallGrid(wallGrid, width, height);
    const rle = encodeTileGridRLE(flat);

    const sourceTilesBytes = flat.length;
    const rleBytes = Buffer.from(rle, 'base64').length;
    const written = emitBundle({
        elements: data.elements,
        customTileTypes: customFiltered,
        rle,
        width,
        height,
        sourceTilesBytes,
        rleBytes,
    });

    console.log(`[encodeMap] wrote: ${path.relative(ROOT, output)} (${written} chars)`);
    console.log(`[encodeMap] tiles: ${width}x${height}, raw=${sourceTilesBytes}B, rle=${rleBytes}B (${(100 * rleBytes / sourceTilesBytes).toFixed(1)}%)`);
    console.log(`[encodeMap] elements: ${data.elements.length}, custom tile types: ${customFiltered.length}`);
})();
